# https://dev.to/dastasoft/present-like-a-pro-with-fusuma-and-markdown-4jge
meta:
  url:
  title: A View on Vue3
  description:
  siteName:
  sns: []
slide:
  loop: false
  ui:
    sidebar: false
    vertical: false
    pagination: bullets # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    languages:
      - javascript
      - typescript
      - vue
      - react
      - html
      - json
    plugins:
      - line-numbers
      - highlight-keywords
    theme: tomorrow #default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
